version: '2'
services:
  jhipster1-app:
    image: jhipster1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipster1-mongodb:27017/?waitQueueMultiple=1000
      - SPRING_DATA_MONGODB_DATABASE=jhipster1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  jhipster1-mongodb:
    extends:
      file: mongodb.yml
      service: jhipster1-mongodb
